stages:
  - deploy

deploy:
  image:
    name: minio/mc
    entrypoint: ['']
  stage: deploy
  before_script:
    - rm -rf -- ..?* .[!.]*
    - mc alias set minio $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
  script:
    - mc mirror --overwrite --remove ./ minio/fonts
